GET http://127.0.0.1:8081/connections HTTP/1.1
# User-Agent: rest-client
# Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
# Content-Type: application/json

####

POST http://127.0.0.1:8081/connection/1 HTTP/1.1

{
    "command": "ls -la",
    "id":1
}